// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BrewWithNullableTypes : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206061333589_BrewWithNullableTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT/bu3/8o/WpZEJvRS229zv0Byt+bOz5dZEX5Q+/152Soz6upzsUPueOz5XlVL75O3/s7Ozvv1fnju07oNoriq3xarH4khT8EKdT2m3t+U7Tlz0G3T/NmWherHwZnxsTios5nBc1u83PReUPNphj5z0Xvzcv1pCympucnVVXm2fK95+951rRk6IvzIrcS9pSk500BJt4I7NaaAm7Cj/REgKYoz5uR/ZG2Cbo9tgT++SlyfWCviRzr9yXGhzsk1G3dbkb/NmCeFcuimX8NOC+yy+KCGSEqWB+lr/JS+GRerCQaGUMN/f7m+2d1tXhVAb738e//ulrXU/B11f/uTVZf5O3tVOBx01TTghHwdKDpPBzK6XKWbsBE5tXgT9O4LttiRWxI3X720bd6lImD"
                       + "M8h74AwlQoC7IXYE8Mvl07zM2zw9Zlv32UcnWTPNZv05IVrMwk9Ilec1dGpWUlhJ5jIrlm1f7xdLwiQrh9HuvHJLYwGULPDuN0/zVb6Evh+m/W16dXq837ftokOmm6jy+K7HPn3DSu+09EZem/hLQ298nr/rEEvfeZ23nsnQAJq0huNeZQo/vu5zVghKxh6DYljrBgCgeex1YfTOyx5NQghWpL0WEYnvTs9msbOoWix787tZ0DwAlk5deQmHFFErdqrtd4/vShZGP3h8dyBd8/iLbLUiU+Clb/ST9LXkbk62X79/fmYhMO5Om0iaxmJreyI3K7vIO99S14Tps6JuWlL32SSDcTqZLXrNbsnYprcIf/enzHCaeQm/O1YKc1mBMPSVgYJ4RkNcQI+wU+lN+8a3U6TTsjKrO+YLmuSkKteL5bBWG37b+YM+DPfp7SFpUscHox/dHkYfk/fFwuVbfCju09tDChIoAYH9L/rwHt/tTHNPy/d4qiPkXT69FRcblfGBDBxXfbfg3aEX/9/OthqW+GD0o9vDCDIaPqTgi9vDC5IUIet5X9w9uj08P+8QAvS/eQ8MbWATQLOf3h5SGNoEQht88/8aQRPj/oFi1s9vMJSbhCz+2s+OiDk/1Ycx7L0OQ/p/l7AGCQEfUvDF7eH9v0EUhiCaUN+HZT57LygSuXfAyIe3h+NCdx+Q+/SHLOI9l7nbxPaun9i/rcus7uoXNy579vxXafJRSiS6LGbwXV9fN22+GKPB+PUvKk9KqHnX4ItsWZznTfumeptjCZfc66+/cmrTj00zK/9fvHxagAI3pl7fM//VTYEuL7N6Os/qfr7r/TJTwarmNwV0A6JfG2Z3TfKbwjWy5BgFLYnV/0+vKP6/hjFvBVht5DcMNbKO9zWnO8ZKvWW6bxB2fxXumwPeyfhPiva9CRvL9s+Ixdrixmz/rQXn52aB7WdFbLoLY9zJe8L4/5joRRa1/v/CwX1g4XrVbWh4m2F2"
                       + "lqNi2N0GTHc56nZwvtlFIJPNFgx+WCs1YTL7ayw7fa2lnsH81G1UFcbxXss7t+rn/wULOv30eHeuNAry1J1x6m9Y0ZFAhRh7UtEcC0OHK0Kdae32ZVix1435ItbD0AJIF7hwWg+0fBwDHF2a+VlcKQpH72dK+9zSlSjvnej61jeyGtQPYYk710voMPmL3LziwoF4TDCX+TTgS9sGEYARkA5GpklHf36RtxnpzOy4bovzbNrS19O8aSjI/ij9yaxc54irJvnsbPnlul2tWxpyvpiU1z4xIGab+uclrxDnx1+y3+rF7F9/CIRmAbX/5fLJuihnFu9nEfdsAATkVz0izGULz+ji2kJ6US1vCUjJ99SonTf5YlUSsObL5evsMh/G7WYahhR7/LTILups0SgM9z79Sew3W7w7+n8CAAD//9RQZRahLgAA"; }
        }
    }
}
