// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Brew : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206061242412_Brew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT/bu3/8o/WpZEJvRS229zv0Byt+bOz5dZEX5Q+/152Soz6upzsUPueOz5XlVL75O3/s7Ozvv1fnju07oNoriq3xarH4khT8EKdT2m3t+U7Tlz0G3T/NmWherHwZnxsTios5nBc1u83PReUPNphj5z0Xvzcv1pCympucnVVXm2fK95+951rRk6IvzIrcS9pSk500BJt4I7NaaAm7Cj/REgKYoz5uR/ZG2Cbo9tgT++SlyfWCviRzr9yXGhzsk1G3dfgPoPyuWRTP/OoBeZJfFBbNCVLQ+Sl/lpXDKvFhJPDKGIvr9zffP6mrxqkIH3se//+tqXU/B2VX/uzdZfZG3t1OCx01TTQtGwNOCpvNwKKfLWboBE5lZgz9N5LpsixUxInX72Uff6lEmDs4g"
                       + "74EzlAgB7obYEcAvl0/zMm/z9Jit3WcfnWTNNJv154RoMQs/IWWe19CqWUmBJRnMrFi2fc1fLAmTrBxGu/PKLc0FULLAu988zVf5Ehp/mPa36dVp8n7ftosOmW6iyuO7Hvv0TSu909IbeW0iMA2+8Xn+rkMsfed13npGQ0No0huOe5Up/Ai7z1khKBl7DIphrRsAgOax14XROy97NAkhWJH2WkQkvjs9m8XOomqx7M3vZkHzAFg6deUlHFJErdiptt89vit5GP3g8d2BhM3jL7LVioyBl8DRT9LXkr052X79/hmahcC4O20iiRqLre2JHK3sIu98S10Tps+KumlJ32eTDOr9ZLboNbslY5veIvzdnzLDaeYl/O5YKcxmBcLQVwYK4hkNcQE9wm6lN+0b306RUMvKrO6YL2iSk6pcL5bDWm34becR+jDcp7eHpGkdH4x+dHsYfUzeFwuXcfGhuE9vDylIoQQE9r/ow3t8tzPNPS3f46mOkHf59FZcbFTGBzJwXPXdgneHXvx/O9tqYOKD0Y9uDyPIafiQgi9uDy9IU4SsZ76ImJdN8PzMQwjQ/+Y9INrQJoBmP709pDC4CYQ2+Ob/NYImxv0Dxayf4WAoNwlZ/LWfHRFzfqoPY9h7HYb0/y5hDVICPqTgi9vD+3+DKAxBNMG+D8t89l5QJHbvgJEPbw/Hxe4+IPfpD1nEey5zt4ntXT+xf1uXWd3VL25c+Oz5r9Lko5RIdFnM4Lu+vm7afDFGg/HrX1SelND/rsEX2bI4z5v2TfU2xyIuuddff+3UJiCbZlb+v3gBtQAFbky+vmcKqZsEXV5m9XSe1f2M1/uluIJ1zW8K6CCiHwCzuyr5TeEaWXSMgpbU6v+n1xT/X8OYtwKsNvIbhhpZyfua0x1jpd5C3TcIu78O980B7+T8J0X73oSN5ftnxGJtcWOe+9aC83OzxPazIjbdpTHu5D1h/H9M9CLLWv9/4eA+sHDF6jY0vM0wOwtS"
                       + "Xxu77oLULQF9s8tAJp8tKPyw1mrCdPbXWHj6Wos9gxmq2ygrjOO9Fnhu1c//C5Z0+gny7lxpHOQpPOPW37CmI6EKcfakojkWjg7XhDrT2u3LsGKvG/NFrIehJZAucOG0Hmj5OAY4ujjzs7hWFI7ez5X2uaUrUd470RWub2Q9qB/EEneul1Bi8hc5esWFA/GYYC7zacCXtg1iACMgHYxMk44C/SJvM1Ka2XHdFufZtKWvp3nTUJj9UfqTWbnOEVlN8tnZ8st1u1q3NOR8MSmvfWJAzDb1z4teIc6Pv2TP1Yvav/4QCM0Cev/L5ZN1Uc4s3s8ien8ABORXfSLMZQvf6OLaQnpRLW8JSMn31KidN/liVRKw5svl6+wyH8btZhqGFHv8tMgu6mzRKAz3Pv1J7DdbvDv6fwIAAP//RpHheaUuAAA="; }
        }
    }
}
