// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class TemperatureAggregate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206070931467_TemperatureAggregate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT/bu3/8o/WpZEJvRS229zv0Byt+bOz5dZEX5Q+/152Soz6upzsUPueOz5XlVL75O3/s7Ozvv1fnju07oNoriq3xarH4khT8EKdT2m3t+U7Tlz0G3T/NmWherHwZnxsTios5nBc1u83PReUPNphj5z0Xvzcv1pCympucnVVXm2fK95+951rRk6IvzIrcS9pSk500BJt4I7NaaAm7Cj/REgKYoz5uR/ZG2Cbo9tgT++SlyfWCviRzr5iezEvh/CC+9zpdNVTuOvCVdv4Zv8yK7LC54EqNC8VH6Ki9ljufFSiKJMVTI72++f1ZXi1cV4Hsf//6vq3U9BRGq/ndvsvoib7+m+nqTL1bQFOs6P74gg0O4/8jtCdEErW9GdTOM785z60J8bXEIBOFpRfJ6"
                       + "E4whNjhummpa8Oi9QRoeDJE4Xc7SDQwp8mTYmMRnXbbFijQJdfvZR9/qjSkOzvCwB84IRAhwN8SOAH65fJqXeZunx+yufPbRSdZMs1mfmkSLWfgJsW9eg4+ykjID5PFkxbLt83qxJEyychjtziu3FBCgZIF3v3mar/IleHyY9rfp1Znift+2iw6ZbqLK47se+/SVC73T0ht5rSiY7Ak+z991iKXvvM5bz+q/lBwIWUHHvcoUfoqkz1khKBl7DIphrRsAgOax14XRb3g5plhjwKIKuAvcI3iInjUbXouIVenO/WaZtkOxJOgxz2Yp9gDYSegKYzikiM6yfGS/e3xXsnT6weO7A+m8x19kqxXZdy+9p5+kryW3d7L9+v3zdwuBcXfaRNJ4FlvbE9mt7CLvfEtdE6bPirppyQxkkwwa+2S26DW7pdSY3iLC058yw3nmJfzuWCnMdQaS1tc0CuIZDXEBJcVW2pv2jW+nSLdmZVZ37BvU1ElVrhfLYZU5/LaLF3wY7tPbQ9Kknw9GP7o9jD4m74uFy8f5UNynt4cUJNgCAvtf9OE9vtuZ5p4J6fFUR8jle8ent+JiozI+kIHjqu8WvDv04v/b2VbDVh+MfnR7GEHGy4cUfHF7eEESK2Q974v3gefnpUKA/jfvAdEGvgE0++ntIYWhbyC0wTf/rxE0Me4fKGb9/BdDuUnI4q/97IiYc4J9GMOu8TCk/3cJa5Aw8iEFX9we3v8bRGEIYpAK8gEGX7wHPJsRCoDZT/9fI6TxOOIDhfbmrA9DvUmIbwcmTX82hNpkZXwI5rPbQ5G8jA9DPrk9hAhLDjLjzyoL9eKmbhPbu35i/7Zxk8YsX/jBFI8boRGPt9H4qRvESJOPUiLOZTFDAPP6umnzxRgNxq9/UXlSwta7Bl9ky+I8b9o31ducIlbEWBTElkXWSPj6XuGZTeo1zayMBGdevnMwMPlhpDkLUODGhOZ7ZgW76yTLy6yezrO6n8l+vxUB"
                       + "DXm+WaA/G4i6kOibhRtERxtAy+rLJti3zsZHE7A/nxjzVoDVUfqGoUYW+7/mdMdYqbeW/w3C7i/Vf3PAO8uCk6J9b8LGlgRnxGJtceMayK0F5+dmFf5nRWy6q+fcyXvC+P+Y6EVWvv//wsF9YJFF7a8zxd0l7dtMxgdYpptd/f/PCly4vvt15sJf3f3afBFwxHlZZTfh8c0u7pqFJOn/h7UCG64jfY3l5K+1hDuYGr4Nv2Ic77Vse6t+/l+wUNtfmerOlcaenpF5adZiHSv2VmrpWwkPSTgmFc2xcHS40tuZ1m5fhhV73ZgvYj0MrT12gQun9UDLxzHA0VXRW60A33oBONbtwJJyB42fvbXicBL8tZI+03YF23snunz+jawH9/MXJCTrJdSx/EU+fnHhQDwmmMt8GoiHbYPwz8hpByPTpKPBv8jbjNR/dly3xXk2benrad40lGH5KGXtjqB6ks/Oll+u29W6pSHni0l57RMD0r6pf170DnF+/CUHLV7C5usPgdAsYMG+XD5ZF+XM4v0sYn4GQECNqHXGXLaw0hfXFtKLanlLQEq+p0b7gf1LsPyXy9fZZT6M2800DCn2+GmRXdTZolEY7n36k9hvtnh39P8EAAD//7IJRcPDNAAA"; }
        }
    }
}
