// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BrewStatusIsNowAnEnum : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206070717256_BrewStatusIsNowAnEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT/bu3/8o/WpZEJvRS229zv0Byt+bOz5dZEX5Q+/152Soz6upzsUPueOz5XlVL75O3/s7Ozvv1fnju07oNoriq3xarH4khT8EKdT2m3t+U7Tlz0G3T/NmWherHwZnxsTios5nBc1u83PReUPNphj5z0Xvzcv1pCympucnVVXm2fK95+951rRk6IvzIrcS9pSk500BJt4I7NaaAm7Cj/REgKYoz5uR/ZG2Cbo9tgT++SlyfWCviRzr5iezEvh/CC8RoLrdjNBtiPSsWBbN/GvAeZFdFhc8tVFR+Sh9lZcy8/NiJfHFGIrl9zffP6urxasK8L2Pf//X1bqegjRV/7s3WX2Rt7dTasdNU00LRsDTaqbzcCiny1m6ARNhW4M/cem6bIsVMRZ1+9lH3+pR"
                       + "Jg7OIO+BM5QIAe6G2BHAL5dP8zJv8/SYrddnH51kzTSb9eeEaDELPyHlnNfQkllJgSIZwKxYtn1NXiwJk6wcRrvzyi3VP1CywLvfPM1X+RIafJj2t+nVaeZ+37aLDpluosrjux779E0lvdPSG3ltIioNpvF5/q5DLH3ndd56RkBDYlKKjnuVKfyIuc9ZISgZewyKYa0bAIDmsdeF0TsvezQJIViR9lpEJL47PZvFzqJqsezN72ZB8wBYOnXlJRxSRK3YqbbfPb4reRX94PHdgQTM4y+y1YosnZeQ0U/S15KNOdl+/f4Zl4XAuDttIokXi63tiRyn7CLvfEtdE6bPirppSd1nkwzW5mS26DW7JWOb3iL83Z8yw2nmJfzuWCnMTgXC0FcGCuIZDXEBPcJuojftG99OkSDLyqzumC9okpOqXC+Ww1pt+G3n4fkw3Ke3h6RpGh+MfnR7GH1M3hcLl0HxobhPbw8pSIkEBPa/6MN7fLczzT0t3+OpjpB3+fRWXGxUxgcycFz13YJ3h178fzvbaqDhg9GPbg8jyFH4kIIvbg8vSDuErOd98T7wGi+TEAL0cwzvAdGGKgE0++ntIYXBSiC0wTf/rxE0Me4fKGb9jAVDuUnI4q/97IiY81N9GMPe6zCk/3cJaxDi+5CCL24P7/8NojAEMQjefYDBF+8FT2L4Diz58PZwXBDvA3Kf/pCFvec8d5vY3vUT+7d1ntVx/eLGJc2eJytNPkqJRJfFDF7s6+umzRdjNBi//kXlSQmF7xp8kS2L87xp31RvcyzPkqP99VdFbWqxaWbl/4uXRgtQ4Ma06numpLrpzeVlVk/nWd3PKr5fjipYsfymgH4golGY3fXGbwrXyHJiFLQkTf8/vVr4/xrGvBVgtZbfMNTIGt3XnO4YK/WW4L5B2P0Vtm8OeCebPyna9yZsLJM/IxZrixsz+bcWnJ+bxbOfFbHpLnpxJ+8J4/9johdZsPr/Cwf3gUXWor7OFHdW"
                       + "omLo3IY83ZWo28H5Ztd/TCJbMPhhLdKEeeyvseL0tVZ5BlNTt9FNGMd7rezcqp//F6zl9DPj3bnSsMfTb8aLv2ExRyITYuxJRXMsDB0uBnWmtduXYcVeN+aLWA9Dax9d4MJpPdDycQxwdFXmZ3GRKBy9nyTtc0tXorx3oktb38hCUD9mJe5cL6HD5C/y64oLB+IxwVzm04AvbRu4/EZAOhiZJh39+UXeZqQzs+O6Lc6zaUtfT/Omoaj6o5R1PAKpST47W365blfrloacLybltU8MiNmm/nm1K8T58ZfsqHpB+tcfAqFZQO1/uXyyLsqZxftZxB8bAAH5VRcIc9nCFbq4tpBeVMtbAlLyPTVq502+WJUErPly+Tq7zIdxu5mGIcUePy2yizpbNArDvU9/EvvNFu+O/p8AAAD//60hivduLgAA"; }
        }
    }
}
