// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class RemovedUnneededColumnsForBrewToKeepItLean : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206070731245_RemovedUnneededColumnsForBrewToKeepItLean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT/bu3/8o/WpZEJvRS229zv0Byt+bOz5dZEX5Q+/152Soz6upzsUPueOz5XlVL75O3/s7Ozvv1fnju07oNoriq3xarH4khT8EKdT2m3t+U7Tlz0G3T/NmWherHwZnxsTios5nBc1u83PReUPNphj5z0Xvzcv1pCympucnVVXm2fK95+951rRk6IvzIrcS9pSk500BJt4I7NaaAm7Cj/REgKYoz5uR/ZG2Cbo9tgT++SlyfWCviRzr5iezEvi/Fy+9yC6LC6ZllDc/Sl/lpZB6XqzEoR9Dkn9/8/2zulq8qtCB9/Hv/7pa11PgUvW/e5PVF3l7Oy1y3DTVtGAEPDViOg+HcrqcpRswET4x+BNbrMu2WNFMUrefffStHmXi4AzyHjhDiRDgbogdAfxy"
                       + "+TQv8zZPj9lcfPbRSdZMs1l/TogWs/AT0oZ5DbWUlRSZkcXJimXbV53FkjDJymG0O6/cUt8CJQu8+83TfJUvoTKHaX+bXp0q7Pdtu+iQ6SaqPL7rsU/fNtE7Lb2R1yaE0egVn+fvOsTSd17nrad1NQYlLeS4V5nCD1H7nBWCkrHHoBjWugEAaB57XRi987JHkxCCFWmvRUTiu9OzWewsqhbL3vxuFjQPgKVTV17CIUXUip1q+93ju5LI0A8e3x3IeDz+IlutyLR4GRD9JH0t6Y+T7dfvn+JYCIy70yaS6bDY2p7IU8ku8s631DVh+qyom5YMRzbJoN5PZotes1sytuktwt/9KTOcZl7C746VwnRQIAx9ZaAgntEQF9Aj7Jd5077x7RQZqazM6o75giY5qcr1Yjms1Ybfdi6VD8N9entImhfxwehHt4fRx+R9sXApCx+K+/T2kIIcREBg/4s+vMd3O9Pc0/I9nuoIeZdPb8XFRmV8IAPHVd8teHfoxf+3s6169j4Y/ej2MIKkgA8p+OL28II4P2Q974v3geeH7iFA/5v3gGhjgwCa/fQmSEPRQSC0wTf/rxE0Me4fKGb9FAFDuUnI4q/97IiY81N9GMPe6zCk/3cJaxBT+5CCL24P7/8NojAEMYiWfYDBFz9k0eq5qt0mtnf9xP5tXVV1E7+4ccWu5zdKk49SItRlMYPP+Pq6afPFGA3Gr39ReVJCvboGX2TL4jxv2jfV2xyrj+TWfv1FP5s5a5pZ+f/ilb8CFLgxa/ieqZtu9m55mdXTeVb3k2bvl6cKFuS+KaA/G4h2l9O+KbiR1bIoaMkJ/r9jMez/64x5K8Bqm75hqJElqK853TFW6q0wfYOw+wtI3xzwTrJ6UrTvTdhYonpGLNYWNyaq/1++NvSzIjbdNR3u5D1h/H9M9CLrMf9/4eA+sMhSy81T/M0ub5g8rfT+w1qDCNO0X2NB5WstYgxmXm6jDDCO91q4uFU//y9Yqugn"
                       + "frtzpXFGxG2+Ya1CQgESkElFcywcHa51dKa125dhxV435otYD0Op/S5w4bQeaPk4Bji66PCzuAYSjt7PAfa5pStR3ZRGTya/iXWOfpBI3LleQhfKX+RIFRcOxGOCucynAV/aNvCxjYB0MDJNOurzi7zNSPdmx3VbnGfTlr6e5k3Di/esVBG5TPLZ2fLLdbtatzTkfDEpr31iQMw29c+LOSHOj79kz9CLir/+EAjNAubjy+WTdVHOLN7PInp/AATkV30OzGUL3+Pi2kJ6US1vCUjJ99SonTf5YkXr9Xnz5fJ1dpkP43YzDUOKPX5aZBd1tmgUhnuf/iT2my3eHf0/AQAA//+t0JNIviwAAA=="; }
        }
    }
}
