// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class RecipeIsPublicProperty : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206040906504_RecipeIsPublicProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT+jXj9KvlgWxGb3U1uvcH6D8vbnj00VWlD/0Xn9Ohvq8mupc/JA7PlueV/Xih9H347tO5jZK4qt8Wqx+JIQ/BCHU9pt7flO05c9Bt0/zZloXqx8CY8aE4qLOZwVNbvNz0HdDzaYY989B583L9aQspqbjJ1VV5tnyvSfveda0ZOSL8yK34vWUROdNAQ7eCGyzmiAfos0KkkNjItQ7wOf5u7ajNOSd13nbt/FEW9ePOBVj3wXoDrALSpRUDIqqr+igLPrO97krzo9xku4OeEmPv8hWK2ICz2vST9LX4jKdbL9+f7doITDuTpuId2SxtT2RGswu8s631DVh+qyom5bmOJtkmNKT2aLX7JaTZXqLzFnXBDjim5fwu7zYdyGDCe6AcvR8RkNckOjzaHWs"
                       + "hNUGD1Hffz3NyqzuShTx/0lVrhfLIRO16W2n9X0Y7tPbQ1JfygejH90eRh+T98XCuTk+FPfp7SEFfktAYP+LPrzHdzvT3GUpT/1oy45D0eXTW3GxURcfyMAx14jh3MS7Qy/+v51t1fnwwehHt4cReBI+pOCL28MLvIOQ9bwv3geeb/FDgP437wHRmvEAmv309pBCQx4IbfDND1nQeva028T2bu1qx34+VlsWGFmmQjcV0TNu0uSjlEh1Wcxg2F5fN22+GKPB+PUvKk9K8IBr8EW2LM7zpn1Tvc2RViHb+/WzGTZ2aJpZ+f/ilEYBCtwYN72nX9mNgpaXWT2dZ/XWInt3532d3SC98EGQvjGUummADwIWCe3fA97/68P1n1sGuxU0NVXfBKhIOPwekxljjl6I+4Hw+mHrhwHshKKTon1vosXC0BkxCrLS32gY2g+AQrysKYto5hviULE2hPekoiEIvmEc26FBty8Tj/a6MV/EerDhbYwmt4hi+9b18V1/OeAx8XNx4UBgcWCZM/s4oKYNFJmZWaKhj5Fp0pn4L/I2o4nOjuu2OM+mLX09zZuGkyg/mZXrHNp/ks/Oll+u29W6PW6afDEpr/3xPr67uX8O1UOcH3/JAuq5E19/CIRmAV79cvlkXZQzi/ezCK8OgABXqm4krCiJROAuri2kF9XyloCUfE/zVb6EZn2TL1YlAWu+XL7OLvNh3G6mYUixx0+L7KLOFo3CcO/Tn8R+tLZ09P8EAAD//zX/ZQvQGgAA"; }
        }
    }
}
