// <auto-generated />
namespace BrewBuddy.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialDatabaseVersion : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206040824412_InitialDatabaseVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soyd1fvVkPZtdj08JRlvkzUfpcVlkhMnrvDx/T7R2HgKtj2yH1CWDvX5zvcq5288++qrJ65d1dV6Uud+Qmv5e+XXwAX1EDVd53V6/ys/19bPZR+nd8L273Rfta947wIB+W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5vcS7OY9AKfFo9entiPHw7s4eiHE3Wy6rNmtponuId9AEZfCbQfZ1WxPffJQ+K97ls+f58qKdW4S/yN6ZT+jXj9KvlgWxGb3U1uvcH6D8vbnj00VWlD/0Xn9Ohvq8mupc/JA7PlueV/Xih9H347tO5jZK4qt8Wqx+JIQ/BCHU9pt7flO05c9Bt0/zZloXqx8CY8aE4qLOZwVNbvNz0HdDzaYY9w+/8+dZ05JxLs6L3IrFU2L5NwU4b+MMbhZvsv1tVpD8GNWuVh2f5+/ajrDLO6/ztm+biSauH3EGxr7p7g6wC0qUSwyKqp3ooCz6zme5K06LcW7uDng3j7/IViuaPM/b0U/S1+LqnGy/fn93ZiEw7k6biFdjsbU9kfrKLvLOt9Q1YfqsqJuW5jibZJjSk9mi1+yWk2V6i8xZV3U74puX8Lu82Hf9ggnugHL0fEZDXJDI8mh1rITVBs9O3389zcqs7ooh8f9J"
                       + "Va4XyyHTsultp619GO7T20NSH8gHox/dHkYfk/fFwrknPhT36e0hBf5GQGD/iz68x3c709xlKU/9aMuOI9Dl01txsVEXH8jAMZeG4dzEu0Mv/r+dbdVp8MHoR7eHEXgAPqTgi9vDC6x6yHreF+8Dz7fUIUD/m9tDDM1vIGrBNz9k8ehZwW4T27u1hh2r91gtUGAamQrdwL9nkqTJRymR6rKYwRy9vm7afDFGg/HrX1SelJg51+CLbFmc5037pnqbI4lBFvPr5w6sp940s/L/xQmEAhS4MUp5Txe8G3MsL7N6Os/qrUX27s77upZBMP9BkL4xlLpB9wcBiwTS7wHv//XB8c8tg90KmhqYbwJUJPh8j8mMMUcvoPxAeP0g8YMAxgK/GU0y8rffaODXDzlCvKwZimjVGyI/sRSE96SiIQi+YeTYoUG3LxMB9roxX8R6sAFljCa3iBv7lvHxXT9x/ph4sbhwIJBGX+Y89Q6oaQMlZGaWxoUGBiPTpDPxX+RtRhOdHddtcZ5NW/p6mjcNpxt+MivXOTT3JJ+dLb9ct6t1e9w0+WJSXvvjfXx3c/8cHIc4P/6ShctzBb7+EAjNArz65fLJuihnFu9nEV4dAAGuVL1GWFG6hcBdXFtIL6rlLQEp+Z7mq3wJrfgmX6xKAtZ8uXydXebDuN1Mw5Bij58W2UWdLRqF4d6nP4n9aBXm6P8JAAD//zm1g/36GQAA"; }
        }
    }
}
